FROM centos:7

RUN yum install -y epel-release

RUN yum groupinstall -y development

RUN yum install -y git glibc-static which nodejs

RUN git clone https://github.com/c9/core.git /c9sdk && cd /c9sdk && scripts/install-sdk.sh

RUN cd

RUN mkdir /src

WORKDIR /src

EXPOSE 8181


